FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip
RUN apt-get update && apt-get install -y build-essential libpq-dev
RUN pip install -r requirements.txt

# RUN pip install fastapi uvicorn sqlalchemy psycopg2
# RUN pip install fastapi_utilities

COPY . .
CMD ["python", "main.py"]